name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]
  
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: action/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test